// src/constants/doctors.js
export const DOCTORS = {
  team: [
    {
      id: 1,
      name: "Dr. Sophie Laurent",
      specialty: "Radiologue",
      hospital: "Hôpital Universitaire de Tunis",
      experience: "15 ans d'expérience",
      patients: 12450,
      rating: 4.9,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
      available: true,
      nextSlot: "14:30",
      languages: ["Français", "Anglais", "Arabe"],
      education: "Faculté de Médecine de Tunis",
      bio: "Spécialiste en imagerie médicale avec une expertise en radiologie interventionnelle.",
      phone: "+216 70 123 456",
      email: "sophie.laurent@medai.tn",
      consultationFee: "150 TND",
    },
    {
      id: 2,
      name: "Dr. Marc Dubois",
      specialty: "Pneumologue",
      hospital: "Clinique Internationale",
      experience: "12 ans d'expérience",
      patients: 9870,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
      available: true,
      nextSlot: "15:00",
      languages: ["Français", "Anglais"],
      education: "Université Paris Descartes",
      bio: "Expert en pathologie respiratoire et dépistage du cancer pulmonaire.",
      phone: "+216 71 234 567",
      email: "marc.dubois@medai.tn",
      consultationFee: "180 TND",
    },
    {
      id: 3,
      name: "Dr. Emma Chen",
      specialty: "Neurologue",
      hospital: "Centre Hospitalier Universitaire",
      experience: "18 ans d'expérience",
      patients: 15600,
      rating: 4.9,
      photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=face",
      available: false,
      nextSlot: "Demain 09:00",
      languages: ["Français", "Anglais", "Mandarin"],
      education: "Johns Hopkins University",
      bio: "Neurologue de renommée internationale, spécialisée dans l'imagerie cérébrale.",
      phone: "+216 72 345 678",
      email: "emma.chen@medai.tn",
      consultationFee: "200 TND",
    },
    {
      id: 4,
      name: "Dr. Thomas Bernard",
      specialty: "Cardiologue",
      hospital: "Hôpital Privé de Tunis",
      experience: "10 ans d'expérience",
      patients: 8230,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face",
      available: true,
      nextSlot: "16:15",
      languages: ["Français", "Anglais", "Italien"],
      education: "Université de Lausanne",
      bio: "Cardiologue interventionnel, spécialiste en imagerie cardiaque.",
      phone: "+216 73 456 789",
      email: "thomas.bernard@medai.tn",
      consultationFee: "170 TND",
    },
    {
      id: 5,
      name: "Dr. Julie Moreau",
      specialty: "Oncologue",
      hospital: "Institut de Cancérologie",
      experience: "20 ans d'expérience",
      patients: 18900,
      rating: 4.9,
      photo: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face",
      available: false,
      nextSlot: "Dans 2 jours",
      languages: ["Français", "Anglais", "Espagnol"],
      education: "Institut Gustave Roussy",
      bio: "Oncologue spécialisée en imagerie tumorale et thérapies ciblées.",
      phone: "+216 74 567 890",
      email: "julie.moreau@medai.tn",
      consultationFee: "220 TND",
    },
    {
      id: 6,
      name: "Dr. Pierre Martin",
      specialty: "Radiologue",
      hospital: "Centre d'Imagerie Médicale",
      experience: "8 ans d'expérience",
      patients: 6540,
      rating: 4.6,
      photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face",
      available: true,
      nextSlot: "17:00",
      languages: ["Français", "Arabe"],
      education: "Faculté de Médecine de Sousse",
      bio: "Radiologue expert en imagerie thoracique et scanner volumique.",
      phone: "+216 75 678 901",
      email: "pierre.martin@medai.tn",
      consultationFee: "140 TND",
    },
  ],
};